name: Android

on:
  workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
            
      - name: Install .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
    
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
            distribution: 'microsoft'
            java-version: '17'
        
      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: tools platform-tools platforms;android-34
      
      - name: Install .NET Android workload
        run: |
          dotnet workload install android maui-android
    
      # How to encode keystore as base64 string
      # https://tecadmin.net/base64-encoding-and-decoding-in-bash/
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: src/ChickAndPaddy/x_release.keystore
  
        run: |
          echo $ENCODED_STRING | base64 -d > $SIGNING_KEY_STORE_PATH
      
      - name: Install .NET Android workload
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          sh build.android.sh

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-builds
          path: src/ChickAndPaddy/bin/Release/net8.0-android/publish

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: android-builds
          path: android-builds
      
      # How to create service account JSON file
      # https://github.com/marketplace/actions/upload-android-release-to-play-store
      - name: Upload to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
            packageName: dev.tuyentv.dotnet.maui.social
            releaseFiles: android-builds/dev.tuyentv.dotnet.maui.social-Signed.aab
            track: production
    