
name: Publish app(s)

on:
  workflow_dispatch:
    inputs:
      RUN_ID:
        description: 'Run ID'
        type: string
        required: true
        default: '9310748902'

permissions: read-all

jobs:
  playstore:
    runs-on: ubuntu-latest

    steps:
      - name: Download app bundle
        uses: actions/download-artifact@v4
        with:
          pattern: '*-Signed.aab*'
          path: android-builds
          run-id: ${{ inputs.RUN_ID }}
    
      - name: Listing
        run: |
          ls -a
          ls -a android-builds
      
      # How to create service account JSON file
      # https://github.com/marketplace/actions/upload-android-release-to-play-store
      - name: Upload to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
            packageName: dev.tuyentv.dotnet.maui.social
            releaseFiles: android-builds/dev.tuyentv.dotnet.maui.social-Signed.aab
            track: production